extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_sm64_material_lights;
extern Vtx ccm_dl_Cube_mesh_vtx_0[24];
extern Gfx ccm_dl_Cube_mesh_tri_0[];
extern Gfx mat_ccm_dl_sm64_material[];
extern Gfx ccm_dl_Cube_mesh[];
extern Gfx ccm_dl_material_revert_render_settings[];
