#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "stomp_smoke/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "pointer/geo.inc.c"
#include "verio/geo.inc.c"
#include "jurio/geo.inc.c"
#include "merio/geo.inc.c"
#include "halo/geo.inc.c"
#include "liftrock/geo.inc.c"
#include "plant/geo.inc.c"
#include "tornado_psy/geo.inc.c"
#include "leaf/geo.inc.c"
#include "growth/geo.inc.c"
#include "spire/geo.inc.c"
#include "glacier/geo.inc.c"
#include "ground/geo.inc.c"
#include "frost_spire/geo.inc.c"
#include "puddle/geo.inc.c"
#include "chest/geo.inc.c"
#include "bully/geo.inc.c"
#include "scuttlebug/geo.inc.c"
#include "porky/geo.inc.c"