#include "src/game/envfx_snow.h"

const GeoLayout porky_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 169, 0, porky_base_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_arml_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -94, 214, 0, -90, 0, 90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, porky_arml_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_forearml_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 84, 0, porky_forearml_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_handl_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 80, 0, porky_handl_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_armr_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 92, 214, 0, -90, 0, -90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, porky_armr_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_forearmr_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 84, 0, porky_forearmr_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_handr_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 80, 0, porky_handr_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_head_skinned),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 214, 0, porky_head_mesh),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_thighl_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -72, 0, 0, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, porky_thighl_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_legl_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 42, 0, porky_legl_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_footl_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 90, 0, porky_footl_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_thighr_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, porky_thighr_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_legr_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 42, 0, porky_legr_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_footr_skinned),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 90, 0, porky_footr_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, porky_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
