extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_sm64_material_lights;
extern Vtx wf_dl_Cube_mesh_vtx_0[24];
extern Gfx wf_dl_Cube_mesh_tri_0[];
extern Gfx mat_wf_dl_sm64_material[];
extern Gfx wf_dl_Cube_mesh[];
extern Gfx wf_dl_material_revert_render_settings[];
