extern const GeoLayout star_switch_opt1[];
extern const GeoLayout star_switch_opt2[];
extern const GeoLayout star_switch_opt3[];
extern const GeoLayout star_geo[];
extern u8 star_stareye_ia8[];
extern u8 star_redstar_ci8[];
extern u8 star_redstar_ci8_pal_rgba16[];
extern u8 star_star_ci8[];
extern u8 star_star_ci8_pal_rgba16[];
extern u8 star_purplestar_ci8[];
extern u8 star_purplestar_ci8_pal_rgba16[];
extern u8 star_bluestar_ci8[];
extern u8 star_bluestar_ci8_pal_rgba16[];
extern Vtx star_001_displaylist_mesh_vtx_0[8];
extern Gfx star_001_displaylist_mesh_tri_0[];
extern Vtx star_000_displaylist_mesh_vtx_0[12];
extern Gfx star_000_displaylist_mesh_tri_0[];
extern Gfx mat_star_eyes[];
extern Gfx mat_revert_star_eyes[];
extern Gfx mat_star_red[];
extern Gfx mat_revert_star_red[];
extern Gfx mat_star_star[];
extern Gfx mat_revert_star_star[];
extern Gfx mat_star_purple[];
extern Gfx mat_revert_star_purple[];
extern Gfx mat_star_blue[];
extern Gfx mat_revert_star_blue[];
extern Gfx star_001_displaylist_mesh[];
extern Gfx star_000_displaylist_mesh[];
extern Gfx star_000_displaylist_mesh_mat_override_star_0[];
extern Gfx star_000_displaylist_mesh_mat_override_purple_1[];
extern Gfx star_000_displaylist_mesh_mat_override_blue_2[];
extern Gfx star_material_revert_render_settings[];
